### ISSUE TITLE
[BUG] Using railway postgres with Ponder 0.6.0 results in error: `relation "public.kysely_migration" does not exist at character 15` 

### ISSUE THREAD

**Issue by swan-of-bodom** [ponder-sh/ponder#1167]
Since the update to 0.6.0+, I have been getting this error when deploying to railway:

```
2024-10-12 00:19:00.046 UTC [2] LOG:  database system is ready to accept connections
2024-10-12 00:20:32.615 UTC [82] ERROR:  relation "public.kysely_migration" does not exist at character 15
2024-10-12 00:20:32.615 UTC [82] STATEMENT:  SELECT * FROM public.kysely_migration LIMIT 1
```

To reproduce:

1. `pnpm create ponder` and select the reference erc20
2. create service on railway and follow steps on docs
3. create pg service on railway and add `DATABASE_URL`

To see how it was working correctly before, do the same steps as above except use `pnpm create ponder@0.5.23`

**Comment by 0xOlias** [comment]
Resolved in DMs. The issue was a combination of:
- The `ERROR:  relation "public.kysely_migration" does not exist at character 15` error was a red herring, that query happens shortly after startup to determine if we need to migrate the sync store from `0.2` -> `0.3`
- The Railway Postgres viewer made it look like there are no tables / data. This is because it only displays tables (and views?) present in the `public` schema. We removed the publish schema pattern in `0.6`, so the actual tables were only present in the deployment-specific schema.

This will be resolved by the new table layout pattern in `0.7` (#1154). Also, we can likely remove the `0.2` -> `0.3` migration code - that's ancient history.
