### ISSUE TITLE
FlushError: unique constraint failed in findMany

### ISSUE THREAD

**Issue by jjranalli** [ponder-sh/ponder#1195]
trying to migrate from a subgraph and stumbled upon this flushError. the issue is triggered by a findMany with filtering, where a unique constraint fails, but the filter condition seems correct. 

<img width="1041" alt="Screenshot 2024-10-27 at 19 21 01" src="https://github.com/user-attachments/assets/fdad8238-9138-49e8-9f25-ebaf5fcce3cf">

the issue can be reproduced on this branch. am I doing something wrong? https://github.com/slice-so/indexer/blob/flusherror-issue/src/SliceCore.ts#L65

**Comment by kyscott18** [comment]
I was able to reproduce this and determine that the underlying problem is that a `Payee` with the id `0xAe009d532328FF09e09E5d506aB5BBeC3c25c0FF` is being created twice. It many be better to use `upsert` here to avoid adding duplicates.

https://github.com/slice-so/indexer/blob/5a42c30a66a6701411d43d9fa1188a46fc71d33f/src/SliceCore.ts#L79-L83

The error that was printed was super unhelpful so I will work on that, but going to close this issue for now.
