### ISSUE TITLE
[BUG]: Indexing history blocks failed in 0.8.3

### ISSUE THREAD

**Issue by CrazyNorman** [ponder-sh/ponder#1338]
After upgrading from 0.7.17 to 0.8.3, I encountered an issue where history blocks could not be indexed. The sync process appears to work well, but the indexing process remains stuck at “Waiting to start.”

**Comment by typedarray** [comment]
Hi, thanks for opening - we'll need more details to help here. Could you share your config and indexing function files? Have you read the [migration guide](https://ponder.sh/docs/migration-guide#08), and are you sure you've registered the indexing functions properly?

**Comment by cryptofelon** [comment]
Think I'm experiencing the same thing. Wish I had an error log to provide you.
Historical blocks sync but they don't index. Live blocks sync and they do index.

Actually, I'm experiencing this with this[ ENS Governor contract indexing code](https://github.com/gskril/ens-governor-app/tree/main/indexer/src) (but I've migrated it from 0.07 to 0.08 on my end).

This is a good example to reproduce with, because it indexes proposal creation and proposal votes, where votes cannot be applied until proposal creation has already happened.
Votes are coming in now, so you'll see it error that there are no proposals to modify for such votes in the db because votes are live indexed and proposal creation happens from historical indexing.
