### ISSUE TITLE
[Feature] Concurrent indexing

### ISSUE THREAD

**Issue by 0xOlias** [ponder-sh/ponder#346]
Consider a simple Ponder app that just inserts ERC20 `Transfer` events into the database.

```graphql
# schema.graphql

type TransferEvent @entity {
  id: String!
  amount: BigInt!
  from: Account!
  to: Account!
  timestamp: Int!
}
```

```ts
// src/index.ts

import { ponder } from "@/generated";

ponder.on("ERC20:Transfer", async ({ event, context }) => {
  const { TransferEvent } = context.entities;

  await TransferEvent.create({
    id: event.log.id,
    data: {
      from: event.params.from,
      to: event.params.to,
      amount: event.params.value,
      timestamp: Number(event.block.timestamp),
    },
  });
});
```

Note that the event handler logic is isolated. You could process all the `Transfer` events concurrently without running into any race conditions or database errors.

Contrast this with a handler that looks like:

```ts
// src/index.ts

import { ponder } from "@/generated";

ponder.on("ERC20:Transfer", async ({ event, context }) => {
  const { Account } = context.entities;

  await Account.upsert({
    id: event.params.to,
    create: {
      balance: event.params.value,
    },
    update: (current) => ({
      balance: current.balance + event.params.value
    }),
  });
});
```

In this case, you couldn't safely run two `Transfer` events with the same `event.params.to` value concurrently - you have a race condition.

This is probably a small research project followed by a large and challenging engineering project.

Open questions
- What concurrency/parallelism model should we use? Vitest test runner might be good inspiration here.
- What does the user-facing API look like? Opt-in, opt-out, automatically detected?

**Comment by kyscott18** [comment]
## Summary

Theoretically, the only thing blocking parallelism is a read-write relationship. 

If task A reads a table that task B wrote to, task A must be run after task B. This logic is irrespective of whether task A and task B are of the same indexing function or not.

Ideally this can be done with no api changes, and instead parse the AST to determine which tables each indexing function reads and writes from.  

Next the indexing service would need to be changed in order to enforce a more sophisticated ordering invariant.  

All of this logic should be designed with indexing function caching in mind.  

I referenced a lot of existing solutions when designing our solution. Our events can be ordered into a directed acyclic graph, which can then be ordered with an algorithm known as topological sort.  

## AST Parsing

  Statically parse the abstract syntax tree with a vite plugin. There are a few tools such as @babel/traverse or acornjs that can be useful for this task. https://github.com/estree/estree/blob/master/es5.md is a spec for the AST. A few edge cases that must be handled: 
  
- Helper functions
- Variable renaming
- Accessing global variables 

The output of the AST parsing step should be a matrix that maps the relationship between indexing functions and the tables they read and write.

##   Special Indexing Functions

There are some special indexing functions that are outside of the typical read-write relationship that can still be optimized. 

- Commutative logic (changing the ordering doesn’t change the result)
- Last-only logic (overwriting a certain variable such that only the last indexing function needs to be ordered correctly)
- Multi-network indexing function that are completely isolated
- Child contracts that are isolated from other child instances

## Indexing Service

The indexing service should consist of:

- an array of un-run events for each indexing function
- a checkpoint for each indexing function
- a helper function that takes an event and processes it
- a helper function that takes an events and returns the next events that are able to be run
- a start function that runs all indexing functions that are able to be run 

## API  

The best solution involves no API changes. Because of the special types of indexing function logic that might be incredibly difficult to detect, we could add some config to notify ponder to treat them specially. 

## Miscellaneous thoughts 

- We could eventually solve for this by doing more optimization around the keys used, specifically if they are coming directly from “event”.
- A super advanced version of this could actually break apart indexing functions into separate logic segments, with some being parallelizable and some not
