### ISSUE TITLE
block range is too wide

### ISSUE THREAD

**Issue by 0xDaksh** [ponder-sh/ponder#531]
Details: block range too wide 15

Version: vie@1.20.0)
2:21:46 Log filter task failed, retrying... [26868245, 26918244] (contract=Contract_Name, network=someTestnet, error=RpcRequestError: PC Request failed. PM WARN historical

Granted this is an rpc issue, but there's no commercial rpc available for this particular network and I wish there was a way to configure it to have smaller blockDelta

**Comment by 0xOlias** [comment]
Hi! You can set the `maxBlockRange` config option for your contract(s). https://ponder.sh/docs/api-reference/config#contracts

Can you share which RPC URL/provider you're using? Our goal is to handle as many of these kinds of errors as we can, so that users don't run need to set `maxBlockRange` if avoidable.

**Comment by joeportela** [comment]
hey @0xOlias just an FYI, I ran into this on Base Sepolia using Alchemy. Specified `2_000` in my contracts config and all was good.
