### ISSUE TITLE
Allow underscore in table/column names

### ISSUE THREAD

**Issue by wyze** [ponder-sh/ponder#953]
I've tested and both Postgresql and Sqlite support underscores in table/column names, so I am curious why it isn't allowed in this function?

https://github.com/ponder-sh/ponder/blob/e7fb08fa9e01ff6bced54c5dc749ca224c4f6296/packages/core/src/build/schema.ts#L313-L323

I've patched the function locally in my project and able to sync without any issues.

**Comment by 0xOlias** [comment]
Hi, thanks for opening. We added this initially to help establish a style convention across Ponder apps (camel case everything), but I agree that it's quite annoying to use camel case rather than snake case for database table/column names. We'll give this some more thought - ideally we can find a solution that allows you to specify the JS name and the database name side-by-side, like Drizzle. In the meantime, I'm hesitant to remove the convention.

Let me know if that solution would work for you / if you have any other thoughts.

**Comment by wyze** [comment]
That is fine, I will just keep my patch around unless it stops working. Thanks! :)
